# TF Syntax Basics

In [1]:
import tensorflow as tf

C:\Users\HP\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(tf.__version__)

1.10.0


In [3]:
hello = tf.constant("Hello")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
 with tf.Session() as sess:
        result = sess.run(hello+world)

In [8]:
result

b'HelloWorld'

In [9]:
a = tf.constant(10)


In [10]:
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [13]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [14]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [16]:
result

30

In [17]:
const= tf.constant(10)


In [18]:
fill_mat = tf.fill((4,4),10)

In [19]:
myzeros = tf.zeros((4,4))

In [20]:
myones = tf.ones((4,4))

In [21]:
myrandn = tf.random_normal((4,4),mean=0, stddev=1.0)

In [32]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [33]:
 my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]
    

In [34]:
sess = tf.InteractiveSession()

C:\Users\HP\Anaconda3\lib\site-packages\tensorflow\python\client\session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [35]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-2.5068736   0.6382461  -0.03694939 -0.8920945 ]
 [ 0.4967799  -1.1085211  -0.17928062  1.2966597 ]
 [-0.37446195 -0.09116874  0.5167054   0.8650745 ]
 [ 0.0100236   0.12650613  0.86964387  1.0859135 ]]


[[0.2595688  0.3266964  0.31751645 0.18617845]
 [0.54241836 0.2956128  0.09812295 0.82180953]
 [0.09964871 0.29917204 0.10963881 0.37307107]
 [0.0739845  0.8150294  0.46034515 0.11769462]]




In [38]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-1.0359873   0.59426594 -0.17761438 -0.33718213]
 [ 0.02914072 -0.0941103   0.36564285  1.0509651 ]
 [ 0.92862856  0.51355684 -1.397956    0.80227786]
 [-1.7077254  -0.39648008  1.2627661   0.9429831 ]]


[[0.81577075 0.3274027  0.7470763  0.08160162]
 [0.918615   0.9153981  0.17966735 0.6043906 ]
 [0.44884908 0.6499685  0.12747025 0.6649108 ]
 [0.43674767 0.5302988  0.9436232  0.35214984]]




In [39]:
a = tf.constant([ [1,2],
                [3,4] ])

In [40]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [42]:
b = tf.constant([[10], [100]])

In [43]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [44]:
result = tf.matmul(a,b)

In [45]:
sess.run(result)

array([[210],
       [430]])

In [46]:
result.eval()

array([[210],
       [430]])