In [4]:
import tensorflow as tf


C:\Users\HP\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [5]:
a = tf.constant([2])
b = tf.constant([3])

In [17]:
c = tf.add(a,b)
c

<tf.Tensor 'Add_5:0' shape=(1,) dtype=int32>

In [16]:
print(c)

Tensor("Add:0", shape=(1,), dtype=int32)


In [8]:
session = tf.Session()

In [10]:
result = session.run(c)
print(result)

[5]


In [15]:
result = session.run(a+b)
print(result)

[5]


In [18]:
session.close()

In [20]:
with tf.Session() as session:
    result = session.run(c)
    print(c)

Tensor("Add_5:0", shape=(1,), dtype=int32)


###second video

In [22]:
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]],[[4,5,6],[5,6,7],[6,7,8]], [[7,8,9],[8,9,10],[9,10,11]] ])


In [26]:
with tf.Session()as session:
    result = session.run(Scalar)
    print('Scalar (1 entry):\n %s \n'% result)
    result = session.run(Vector)
    print('Scalar (3 entry):\n %s \n'% result)
    result = session.run(Matrix)
    print('Scalar (3*3 entry):\n %s \n'% result)
    result = session.run(Tensor)
    print('Scalar (3*3*3 entry):\n %s \n'% result)

Scalar (1 entry):
 [2] 

Scalar (3 entry):
 [5 6 2] 

Scalar (3*3 entry):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Scalar (3*3*3 entry):
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 




# Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(Matrix_one,Matrix_two)

with tf.Session() as session:
    result = session.run(first_operation)
    print('Defind using tensorflow function')
    print(result)

# Variables

In [30]:
state = tf.constant(1)

In [46]:
one =tf.constant(1)
new_value = tf.add(state, one)
# update = tf._assign(state, new_value)

In [47]:
init_op = tf.initialize_all_variables()

In [48]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(state))
    for _ in range(3):
#         session.run(update)
        print(session.run(state))

1
1
1
1


PlaceHolder