# Part_1

In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [42]:
housing = pd.read_csv('house_pricing.csv')

In [43]:
housing.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0              41.0       880.0          129.0       322.0       126.0   
1              21.0      7099.0         1106.0      2401.0      1138.0   
2              52.0      1467.0          190.0       496.0       177.0   
3              52.0      1274.0          235.0       558.0       219.0   
4              52.0      1627.0          280.0       565.0       259.0   

   medianIncome  medianHouseValue  
0        8.3252          452600.0  
1        8.3014          358500.0  
2        7.2574          352100.0  
3        5.6431          341300.0  
4        3.8462          342200.0

In [44]:
housing.describe().transpose()

count           mean            std         min  \
housingMedianAge  20640.0      28.639486      12.585558      1.0000   
totalRooms        20640.0    2635.763081    2181.615252      2.0000   
totalBedrooms     20640.0     537.898014     421.247906      1.0000   
population        20640.0    1425.476744    1132.462122      3.0000   
households        20640.0     499.539680     382.329753      1.0000   
medianIncome      20640.0       3.870671       1.899822      0.4999   
medianHouseValue  20640.0  206855.816909  115395.615874  14999.0000   

                          25%          50%           75%          max  
housingMedianAge      18.0000      29.0000      37.00000      52.0000  
totalRooms          1447.7500    2127.0000    3148.00000   39320.0000  
totalBedrooms        295.0000     435.0000     647.00000    6445.0000  
population           787.0000    1166.0000    1725.00000   35682.0000  
households           280.0000     409.0000     605.00000    6082.0000  
medianIncome           2.5634       3.5348       4.74325      15.0001  
medianHouseValue  119600.0000  179700.0000  264725.00000  500001.0000

In [45]:
housing.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

In [46]:
x_data = housing.drop('medianHouseValue', axis=1)

In [47]:
y_val = housing['medianHouseValue']

In [48]:
x_data.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
0              41.0       880.0          129.0       322.0       126.0   
1              21.0      7099.0         1106.0      2401.0      1138.0   
2              52.0      1467.0          190.0       496.0       177.0   
3              52.0      1274.0          235.0       558.0       219.0   
4              52.0      1627.0          280.0       565.0       259.0   

   medianIncome  
0        8.3252  
1        8.3014  
2        7.2574  
3        5.6431  
4        3.8462

In [49]:
y_val.head()

0    452600.0
1    358500.0
2    352100.0
3    341300.0
4    342200.0
Name: medianHouseValue, dtype: float64

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
 X_train, X_test, y_train, y_test = train_test_split(x_data, y_val, test_size=0.3, random_state=101)

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [53]:
scaler = MinMaxScaler()

In [54]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [55]:
X_train = pd.DataFrame(data=scaler.transform(X_train), columns=X_train.columns, index=X_train.index)
X_train.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
6761          0.352941    0.069688       0.117163    0.048769    0.115442   
3010          0.607843    0.011242       0.015673    0.008367    0.014142   
7812          0.666667    0.025230       0.031347    0.020971    0.030258   
8480          0.666667    0.032530       0.033830    0.024752    0.030094   
1051          0.294118    0.031919       0.035692    0.019466    0.034863   

      medianIncome  
6761      0.142508  
3010      0.045027  
7812      0.212866  
8480      0.298651  
1051      0.272631

In [56]:
X_test = pd.DataFrame(data=scaler.transform(X_test),columns=X_test.columns, index=X_test.index)
X_test.head()

housingMedianAge  totalRooms  totalBedrooms  population  households  \
16086          0.686275    0.046264       0.045158    0.025873    0.048841   
8816           0.705882    0.027417       0.020795    0.012709    0.023187   
7175           0.901961    0.032326       0.040813    0.041662    0.042592   
16714          0.313725    0.043212       0.046089    0.032840    0.048018   
14491          0.411765    0.088433       0.069367    0.043728    0.072192   

       medianIncome  
16086      0.353133  
8816       0.770182  
7175       0.133626  
16714      0.263576  
14491      0.660046

In [57]:
housing.columns

Index(['housingMedianAge', 'totalRooms', 'totalBedrooms', 'population',
       'households', 'medianIncome', 'medianHouseValue'],
      dtype='object')

# Part 2

In [58]:
age = tf.feature_column.numeric_column('housingMedianAge')
rooms = tf.feature_column.numeric_column('totalRooms')
bedrooms = tf.feature_column.numeric_column('totalBedrooms')
pop = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
income = tf.feature_column.numeric_column('medianIncome')

In [59]:
feat_cols = [age,rooms, bedrooms, pop, households,income]

In [60]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=10, num_epochs=1000, shuffle=True)

In [61]:
model = tf.estimator.DNNRegressor(hidden_units=[6,6,6], feature_columns=feat_cols)

W0715 22:26:14.749053 140328147449664 estimator.py:1811] Using temporary folder as model directory: /tmp/tmpduzdt4p0


In [62]:
model.train(input_fn=input_func, steps=25000)

In [63]:
predict_input_func = tf.estimator.inputs.pandas_input_fn(x=X_test, batch_size=10, num_epochs=1, shuffle=False)

In [64]:
pred_gen = model.predict(predict_input_func)

In [65]:
predictions = list(pred_gen)

In [66]:
predictions

[{'predictions': array([233533.78], dtype=float32)},
 {'predictions': array([294005.4], dtype=float32)},
 {'predictions': array([217995.3], dtype=float32)},
 {'predictions': array([184602.45], dtype=float32)},
 {'predictions': array([265448.12], dtype=float32)},
 {'predictions': array([201566.27], dtype=float32)},
 {'predictions': array([228956.53], dtype=float32)},
 {'predictions': array([207392.64], dtype=float32)},
 {'predictions': array([214841.06], dtype=float32)},
 {'predictions': array([183668.53], dtype=float32)},
 {'predictions': array([207031.08], dtype=float32)},
 {'predictions': array([227012.8], dtype=float32)},
 {'predictions': array([194001.34], dtype=float32)},
 {'predictions': array([178679.6], dtype=float32)},
 {'predictions': array([260522.81], dtype=float32)},
 {'predictions': array([176207.12], dtype=float32)},
 {'predictions': array([203286.81], dtype=float32)},
 {'predictions': array([187058.78], dtype=float32)},
 {'predictions': array([181379.67], dtype=float32)

# Part 3

In [67]:
final_pred = []
for pred in predictions:
    final_pred.append(pred['predictions'])

In [68]:
final_pred

[array([233533.78], dtype=float32),
 array([294005.4], dtype=float32),
 array([217995.3], dtype=float32),
 array([184602.45], dtype=float32),
 array([265448.12], dtype=float32),
 array([201566.27], dtype=float32),
 array([228956.53], dtype=float32),
 array([207392.64], dtype=float32),
 array([214841.06], dtype=float32),
 array([183668.53], dtype=float32),
 array([207031.08], dtype=float32),
 array([227012.8], dtype=float32),
 array([194001.34], dtype=float32),
 array([178679.6], dtype=float32),
 array([260522.81], dtype=float32),
 array([176207.12], dtype=float32),
 array([203286.81], dtype=float32),
 array([187058.78], dtype=float32),
 array([181379.67], dtype=float32),
 array([232149.77], dtype=float32),
 array([171866.61], dtype=float32),
 array([234213.39], dtype=float32),
 array([216302.61], dtype=float32),
 array([170174.17], dtype=float32),
 array([191840.39], dtype=float32),
 array([262411.44], dtype=float32),
 array([187387.1], dtype=float32),
 array([148434.72], dtype=float32

In [69]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test,final_pred)**0.5

101583.22077338686